import { getDb } from "../../server/db";
import { inventoryMovements } from "../schema";

export async function seedinventory_movements() {
  const db = await getDb();
  if (!db) {
    console.error("Database not available");
    return;
  }

  console.log("بدء إضافة بيانات inventoryMovements...");

  const data = [
    {
      itemId: 1,
      movementType: "in",
      quantity: 10,
      movementDate: "2024-06-05",
      referenceNumber: "PO-2024-001",
      notes: "استلام محولات كهربائية من المورد (فاتورة شراء رقم 1001)",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 6,
      movementType: "in",
      quantity: 50,
      movementDate: "2024-06-10",
      referenceNumber: "PO-2024-002",
      notes: "توريد قواطع دائرة 500 أمبير",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 11,
      movementType: "in",
      quantity: 200,
      movementDate: "2024-06-15",
      referenceNumber: "PO-2024-003",
      notes: "شراء كابلات نحاسية للمشاريع الجديدة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 16,
      movementType: "in",
      quantity: 150,
      movementDate: "2024-06-20",
      referenceNumber: "PO-2024-004",
      notes: "استلام مصابيح LED صناعية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 21,
      movementType: "in",
      quantity: 30,
      movementDate: "2024-06-25",
      referenceNumber: "PO-2024-005",
      notes: "توريد فلاتر زيت للمولدات",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 26,
      movementType: "in",
      quantity: 15,
      movementDate: "2024-07-01",
      referenceNumber: "PO-2024-006",
      notes: "شراء بطاريات تشغيل جديدة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 1,
      movementType: "out",
      quantity: 2,
      movementDate: "2024-07-05",
      referenceNumber: "WO-2024-001",
      notes: "صرف محول كهربائي لتركيبه في محطة الرياض",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 6,
      movementType: "out",
      quantity: 10,
      movementDate: "2024-07-10",
      referenceNumber: "WO-2024-002",
      notes: "صرف قواطع دائرة لصيانة طارئة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 11,
      movementType: "out",
      quantity: 50,
      movementDate: "2024-07-15",
      referenceNumber: "WO-2024-003",
      notes: "صرف كابلات نحاسية لمشروع التوسعة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 16,
      movementType: "out",
      quantity: 20,
      movementDate: "2024-07-20",
      referenceNumber: "WO-2024-004",
      notes: "صرف مصابيح LED لإضاءة المخزن",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 21,
      movementType: "out",
      quantity: 5,
      movementDate: "2024-07-25",
      referenceNumber: "WO-2024-005",
      notes: "صرف فلاتر زيت للصيانة الدورية للمولد رقم 3",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 26,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-08-01",
      referenceNumber: "WO-2024-006",
      notes: "صرف بطارية تشغيل لاستبدال بطارية تالفة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 1,
      movementType: "adjustment",
      quantity: -1,
      movementDate: "2024-08-05",
      referenceNumber: "ADJ-2024-001",
      notes: "تسوية جرد: نقص محول واحد غير مسجل",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 6,
      movementType: "in",
      quantity: 5,
      movementDate: "2024-08-10",
      referenceNumber: "RTN-2024-001",
      notes: "مرتجع قواطع دائرة من مشروع لم يتم تنفيذه",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 11,
      movementType: "out",
      quantity: 10,
      movementDate: "2024-08-15",
      referenceNumber: "WO-2024-007",
      notes: "صرف كابلات نحاسية لعميل سكني",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 16,
      movementType: "out",
      quantity: 5,
      movementDate: "2024-08-20",
      referenceNumber: "WO-2024-008",
      notes: "صرف مصابيح LED لمكتب الإدارة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 21,
      movementType: "in",
      quantity: 10,
      movementDate: "2024-08-25",
      referenceNumber: "PO-2024-007",
      notes: "توريد إضافي لفلاتر الزيت",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 26,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-09-01",
      referenceNumber: "WO-2024-009",
      notes: "صرف بطارية تشغيل للمولد رقم 1",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 2,
      movementType: "in",
      quantity: 8,
      movementDate: "2024-09-05",
      referenceNumber: "PO-2024-008",
      notes: "استلام محولات كهربائية 50 كيلو فولت",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 7,
      movementType: "out",
      quantity: 15,
      movementDate: "2024-09-10",
      referenceNumber: "WO-2024-010",
      notes: "صرف قواطع دائرة 250 أمبير",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 12,
      movementType: "out",
      quantity: 75,
      movementDate: "2024-09-15",
      referenceNumber: "WO-2024-011",
      notes: "صرف كابلات ألومنيوم لمشروع جديد",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 17,
      movementType: "in",
      quantity: 100,
      movementDate: "2024-09-20",
      referenceNumber: "PO-2024-009",
      notes: "شراء مصابيح LED موفرة للطاقة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 22,
      movementType: "out",
      quantity: 3,
      movementDate: "2024-09-25",
      referenceNumber: "WO-2024-012",
      notes: "صرف فلاتر هواء للمولدات",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 27,
      movementType: "in",
      quantity: 10,
      movementDate: "2024-10-01",
      referenceNumber: "PO-2024-010",
      notes: "توريد بطاريات احتياطية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 3,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-10-05",
      referenceNumber: "WO-2024-013",
      notes: "صرف محول كهربائي لعميل صناعي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 8,
      movementType: "adjustment",
      quantity: 2,
      movementDate: "2024-10-10",
      referenceNumber: "ADJ-2024-002",
      notes: "تسوية جرد: زيادة في قواطع الدائرة بعد إعادة العد",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 13,
      movementType: "out",
      quantity: 20,
      movementDate: "2024-10-15",
      referenceNumber: "WO-2024-014",
      notes: "صرف كابلات أرضية لمشروع جديد",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 18,
      movementType: "out",
      quantity: 10,
      movementDate: "2024-10-20",
      referenceNumber: "WO-2024-015",
      notes: "صرف مصابيح LED لصيانة الشوارع",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 23,
      movementType: "in",
      quantity: 5,
      movementDate: "2024-10-25",
      referenceNumber: "RTN-2024-002",
      notes: "مرتجع فلاتر وقود من ورشة الصيانة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 28,
      movementType: "out",
      quantity: 2,
      movementDate: "2024-11-01",
      referenceNumber: "WO-2024-016",
      notes: "صرف بطاريات تشغيل للمولد رقم 4",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 4,
      movementType: "in",
      quantity: 12,
      movementDate: "2024-11-05",
      referenceNumber: "PO-2024-011",
      notes: "استلام محولات توزيع صغيرة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 9,
      movementType: "out",
      quantity: 8,
      movementDate: "2024-11-10",
      referenceNumber: "WO-2024-017",
      notes: "صرف قواطع حماية من التسرب الأرضي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 14,
      movementType: "out",
      quantity: 30,
      movementDate: "2024-11-15",
      referenceNumber: "WO-2024-018",
      notes: "صرف كابلات توصيل داخلية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 19,
      movementType: "in",
      quantity: 80,
      movementDate: "2024-11-20",
      referenceNumber: "PO-2024-012",
      notes: "شراء مصابيح هالوجين للاستخدام المؤقت",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 24,
      movementType: "out",
      quantity: 4,
      movementDate: "2024-11-25",
      referenceNumber: "WO-2024-019",
      notes: "صرف مواد استهلاكية للصيانة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 29,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-12-01",
      referenceNumber: "WO-2024-020",
      notes: "صرف بطارية تشغيل للمولد الاحتياطي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 5,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-12-05",
      referenceNumber: "WO-2024-021",
      notes: "صرف محول كهربائي لتبديل محول تالف",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 10,
      movementType: "in",
      quantity: 40,
      movementDate: "2024-12-10",
      referenceNumber: "PO-2024-013",
      notes: "استلام قواطع دائرة جديدة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 15,
      movementType: "out",
      quantity: 15,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-022",
      notes: "صرف كابلات للربط الداخلي في المحطة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 20,
      movementType: "adjustment",
      quantity: -5,
      movementDate: "2024-12-14",
      referenceNumber: "ADJ-2024-003",
      notes: "تسوية جرد: نقص في مصابيح LED بعد الجرد السنوي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 25,
      movementType: "in",
      quantity: 20,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-014",
      notes: "توريد أدوات صيانة جديدة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 30,
      movementType: "out",
      quantity: 3,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-023",
      notes: "صرف بطاريات تشغيل للمولد رقم 2",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 1,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-024",
      notes: "صرف محول لعميل تجاري",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 6,
      movementType: "out",
      quantity: 5,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-025",
      notes: "صرف قواطع لتبديل قواطع تالفة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 11,
      movementType: "in",
      quantity: 100,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-015",
      notes: "استلام دفعة جديدة من الكابلات النحاسية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 16,
      movementType: "out",
      quantity: 10,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-026",
      notes: "صرف مصابيح LED لمشروع إضاءة جديد",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 21,
      movementType: "out",
      quantity: 2,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-027",
      notes: "صرف فلاتر زيت للصيانة الوقائية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 26,
      movementType: "in",
      quantity: 5,
      movementDate: "2024-12-14",
      referenceNumber: "RTN-2024-003",
      notes: "مرتجع بطاريات تشغيل زائدة عن الحاجة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 3,
      movementType: "in",
      quantity: 5,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-016",
      notes: "استلام محولات كهربائية 200 كيلو فولت",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 8,
      movementType: "out",
      quantity: 12,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-028",
      notes: "صرف قواطع دائرة 100 أمبير",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 13,
      movementType: "adjustment",
      quantity: 1,
      movementDate: "2024-12-14",
      referenceNumber: "ADJ-2024-004",
      notes: "تسوية جرد: زيادة كابل أرضي واحد",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 18,
      movementType: "in",
      quantity: 50,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-017",
      notes: "شراء مصابيح LED إضافية",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 23,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-029",
      notes: "صرف فلتر وقود لسيارة الصيانة",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 28,
      movementType: "in",
      quantity: 3,
      movementDate: "2024-12-14",
      referenceNumber: "RTN-2024-004",
      notes: "مرتجع بطاريات احتياطية من العميل",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 5,
      movementType: "in",
      quantity: 2,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-018",
      notes: "استلام محولات كهربائية 500 كيلو فولت",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 10,
      movementType: "out",
      quantity: 10,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-030",
      notes: "صرف قواطع دائرة 400 أمبير",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 15,
      movementType: "in",
      quantity: 25,
      movementDate: "2024-12-14",
      referenceNumber: "PO-2024-019",
      notes: "شراء كابلات للربط الداخلي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 20,
      movementType: "out",
      quantity: 5,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-031",
      notes: "صرف مصابيح LED لمشروع داخلي",
      createdBy: 1,
      updatedBy: 1,
    },
    {
      itemId: 25,
      movementType: "out",
      quantity: 1,
      movementDate: "2024-12-14",
      referenceNumber: "WO-2024-032",
      notes: "صرف أداة صيانة خاصة",
      createdBy: 1,
      updatedBy: 1,
    },
  ];

  try {
    await db.insert(inventoryMovements).values(data);
    
    console.log(`✅ تم إضافة ${data.length} سجل بنجاح`);
    return data.length;
  } catch (error) {
    console.error("❌ خطأ في إضافة بيانات inventoryMovements:", error);
    throw error;
  }
}
